FROM normphp/dnmp-php:php-fpm-7.4-universal
MAINTAINER pizepei "pizepei@pizepei.com"
ENV TIMEZONE Asia/Shanghai

COPY ./swoole-4.6.1.tgz         /home/swoole-4.6.1.tgz
COPY ./xdebug-3.0.2.tgz         /home/xdebug-3.0.2.tgz
COPY ./libssh2-1.9.0.tar.gz     /home/libssh2-1.9.0.tar.gz

RUN  echo -e "\033[5;34m 使用php-fpm-7.4-universal基础镜像进行构建 \033[0m"  \
    && echo -e "\033[5;34m COPY swoole-4.6.1.tgz        https://pecl.php.net/get/swoole-4.6.1.tgz  \033[0m"  \
    && echo -e "\033[5;34m COPY xlswriter-1.3.7.tgz     https://pecl.php.net/get/xlswriter-1.3.7.tgz  \033[0m"  \
    && echo -e "\033[5;34m COPY xdebug-3.0.2.tgz        https://pecl.php.net/get/xdebug-3.0.2.tgz  \033[0m"  \
    && echo -e "\033[5;34m 安装需要的依赖包 \033[0m" \
    && apk add  --no-cache autoconf cmake make  gcc g++   \
                                   zlib-dev \
                                   icu-dev \
                                   libtool \
                                   libpq \
                                   bzip2-dev bzip2 \
                                   shadow \
#     && echo -e "\033[5;34m pdo  pdo_pgsql \033[0m"  \
#     && apk add  --update --no-cache postgresql-dev    \
#     && docker-php-ext-install    pdo_pgsql   \

#     && echo -e "\033[5;34m pdo_sqlsrv【32位系统目前无法编译通过 同时 连接sqlsrv时需要编译安装odbc】 \033[0m"  \
#     && apk add  --update --no-cache unixodbc-dev  unixodbc \
#     && pecl install             pdo_sqlsrv \
#     && docker-php-ext-enable    pdo_sqlsrv \

#     && echo -e "\033[5;34m 图像处理 imagick   \033[0m" \
#     && apk add --update --no-cache   imagemagick  imagemagick-dev \
#     && pecl install imagick \
#     && docker-php-ext-enable  imagick \

#     && echo -e "\033[5;34m 非必要扩展 SSH2      https://www.libssh2.org/download/libssh2-1.9.0.tar.gz \033[0m" \
#     && cd /home/ && tar -zxvf libssh2-1.9.0.tar.gz && cd libssh2-1.9.0/  &&  ./configure && make && make install \
#     && pecl install                 ssh2-1.2 \
#     && docker-php-ext-enable        ssh2  \

#     && echo -e "\033[5;34m 非必要扩展 mongodb  \033[0m" \
#     && pecl install                 mongodb \
#     && docker-php-ext-enable        mongodb \

#     && echo -e "\033[5;34m 非必要扩展  \033[0m" \
#     && pecl install             /home/xdebug-3.0.2.tgz \
#     && docker-php-ext-enable    xdebug \

#     && echo -e "\033[5;34m 非必要扩展 swoole  \033[0m" \
#     && printf "y\y\y" | pecl install      /home/swoole-4.6.1.tgz \
#     && docker-php-ext-enable   swoole \


    &&  echo -e "\033[5;34m 设置用户id 1000 \033[0m" \
    && usermod -u 1000 www-data \

    && echo -e "\033[5;34m 删除不需要的文件 \033[0m" \
    && rm -rf   /home/*   \
    && echo -e "\033[5;34m 删除不需要的依赖包 \033[0m" \
    && docker-php-source delete \
    && echo -e "\033[5;34m 注意检查是否安装过，如果删除未安装的包会导致编译构建失败 \033[0m" \
    && apk del \
             autoconf cmake make  gcc g++ zlib-dev libtool \
#              unixodbc           \
#              unixodbc-dev       \
#              postgresql-dev     \
             bzip2-dev bzip2    \
#              imagemagick-dev    \

             shadow             \
    && echo -e "\033[5;34m 删除不需要的缓存 \033[0m" \
    && ls -l  /var/cache/apk    \
    && rm -rf /var/cache/*      \
    && rm -rf /tmp/pear/temp/*  \
    &&  echo -e "\033[5;34m 检查ext \033[0m" \
    && php -m

WORKDIR /data


